"""edit Articles

Revision ID: 994346810ddf
Revises: fdabbdcb1432
Create Date: 2025-07-11 07:57:50.924507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994346810ddf'
down_revision: Union[str, Sequence[str], None] = 'fdabbdcb1432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('articles', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
